[package]
name = "schip8-macroquad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
macroquad = "0.4.2"
rodio = "0.17.1"
schip8 = "0.1.0"
